
#define DEFAUL_ACELERACION_MODE 5

#define DEFAUL_VELOCIDAD_MODO 1

#define LONGITUD_EJE 30

#define DIAMETRO_RUEDA 12,5

#define PULSOS_REVOLUCION 980

#define VELOCIDAD_MODO_GIRO 4

#define MOVILIDAD_DEBUG

/*******************************************************/

#define VELOCIDAD_0_RAMPA 16
#define VELOCIDAD_1_RAMPA 32
#define VELOCIDAD_2_RAMPA 64
#define VELOCIDAD_3_RAMPA 96
#define VELOCIDAD_4_RAMPA 128
